### ISSUE TITLE
Generate target list based on a template

### ISSUE THREAD

**Issue by nmaludy** [EncoreTechnologies/puppet-inventory_utils#1]
Users want to generate a list of hosts given a pattern/range:

```
---
groups:
  - name: mygroup
    targets:
      - webserver[00-99].domain.tld'
```

Would like to facilitate that with a plugin, maybe leveraging ERB?
